baseURL = "https://www.mxvar.com/"
languageCode = "zh-cn"
title = "小梦博客"
theme = "hugo-theme-bootstrap"

[menu]
 
 
[params]
enableEmoji = true
figurePositionLabel = "Figure"
mobileNavigation = "right" # Mobile nav menu will open to the left of the screen.
# The year when ths website was created
since = 2016


